### ISSUE TITLE
用量化工具时遇到了current model is not supported by esp-dl的错误

### ISSUE THREAD

**Issue by xiao-mb** [espressif/esp-dl#58]
Generating the quantization table:
MatMul is not supported on esp-dl yet
Softmax is not supported on esp-dl yet
Traceback (most recent call last):
  File "example.py", line 40, in <module>
    calib.generate_quantization_table(model_proto, calib_dataset, pickle_file_path)
  File "calibrator.py", line 320, in calibrator.Calibrator.generate_quantization_table
  File "calibrator.py", line 209, in calibrator.Calibrator.generate_output_model
  File "calibrator.py", line 204, in calibrator.Calibrator.check_model
ValueError: current model is not supported by esp-dl
用量化工具时遇到了以上错误，要如何修改？

**Comment by Auroragan** [comment]
因为 esp-dl 的 API 暂不支持 matmul 和 softmax, 所以 calibrator 暂不能接受这个模型

**Comment by xiao-mb** [comment]
看例子里的Dense层被优化成Gemm，我模型里的Dense还是matmul，没有被优化为Gemm，这是为什么？

**Comment by Auroragan** [comment]
你这一层没有 bias 吗?

**Comment by xiao-mb** [comment]
有的

**Comment by Auroragan** [comment]
能把模型图发出来看一下吗?

**Comment by xiao-mb** [comment]
![order_model_tf onnx](https://user-images.githubusercontent.com/89243287/132512543-7e10ea40-b0e0-4a1d-b680-128a467678f8.png)
上图是优化前的：
下图是优化后的：
![order_model_tf_optimized onnx](https://user-images.githubusercontent.com/89243287/132512729-6d9cf026-48c4-44e9-b22a-69d5055b3c3d.png)

**Comment by Auroragan** [comment]
试试把 optimizer.py 
https://github.com/espressif/esp-dl/blob/8a5be0973686e8ae16e19a345025a954b5cdc31e/tools/quantization_tool/optimizer.py#L137
```
if not dim[0].dim_param:
    dim[0].dim_param = 'N'
```

改成 固定的batch size:
```
dim[0].dim_param = '20'
```

看一下能不能 fuse 成功

**Comment by xiao-mb** [comment]
![order_model_tf2_optimized onnx](https://user-images.githubusercontent.com/89243287/132541355-24b4167d-1f65-4d5d-9373-a8542aa99573.png)
还是不行

**Comment by Auroragan** [comment]
dim[0].dim_param = ''
dim[0].dim_value = 20

改成这样呢?

**Comment by xiao-mb** [comment]
可以了。能生成模型文件的版本麻烦尽快更新下，谢谢！

**Comment by Auroragan** [comment]
我们 API 将会有所改动, 能生成模型文件的版本将在之后与 API 一起更新

**Comment by xiao-mb** [comment]
> dim[0].dim_param = ''
> dim[0].dim_value = 20
> 
> 改成这样呢?

batch size 的大小有什么讲究吗，把网络移植到s3上后，识别不正确。评估的准确率如下：

> Evaluating the performance on esp32s3:
>accuracy of int16 model is: 0.996094
>accuracy of fp32 model is: 0.996094
把同张图片导出，在PC上测试，识别正确。在S3上，不同的图片大多数会预测出同一个值。这个问题应该从哪些方面来定位原因？
